#### Problem 3
##### Gambler's Ruin Model

In [3]:
import numpy as np

p = np.array([[1,0,0,0,0],
                [1/3,0,2/3,0,0],
                [0,1/3,0,2/3,0],
                [0,0,1/3,0,2/3],
                [0,0,0,0,1]])
print(np.linalg.matrix_power(p,5))

[[1.         0.         0.         0.         0.        ]
 [0.44032922 0.         0.13168724 0.         0.42798354]
 [0.16049383 0.06584362 0.         0.13168724 0.64197531]
 [0.05349794 0.         0.06584362 0.         0.88065844]
 [0.         0.         0.         0.         1.        ]]
