#### Problem 4
##### Markov Chain simulation

In [2]:
import numpy as np

p = np.array([[1/2, 1/2, 0, 0, 0, 0],
            [0, 1/2, 1/2, 0, 0, 0],
            [1/3, 0, 1/3, 1/3,0, 0],
            [0, 0, 0, 1/2, 1/2, 0],
            [0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 1, 0]])

p5 = np.linalg.matrix_power(p,5)
print(p5)

[[0.20717593 0.25347222 0.24537037 0.17592593 0.07638889 0.04166667]
 [0.16358025 0.20717593 0.1716821  0.16358025 0.18287037 0.11111111]
 [0.11445473 0.16358025 0.14994856 0.11445473 0.2029321  0.25462963]
 [0.         0.         0.         0.03125    0.65625    0.3125    ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         1.         0.        ]]


In [26]:
import numpy as np
import random

N = 10000
sim_x = []
x0 = 1
    
    
def markov_step(state):
    if state == 1:
        return random.choice([1, 2])
    elif state == 2:
        return random.choice([2, 3])
    elif state == 3:
        return random.choice([1, 3, 4])
    elif state == 4:
        return random.choice([4, 5])
    elif state == 5:
        return 6
    else:
        return 5
    
count = 0   
for i in range(N):
    x_list = [x0]
    for j in range(5):
        next_state = markov_step(x_list[-1])
        x_list.append(next_state)
    sim_x.append(x_list)
    if x_list[-1] == 4:
        count+=1


print(f'count = {count}')





count = 1780


In [27]:
import numpy as np

# Finding p11
A = np.array([[-0.5,0,1/3],[1/2,1/2,0],[0,1/2,-2/3]])
b = np.array([0,0,0])

v = np.linalg.solve(A,b)
print(v)

[-0.  0. -0.]
