#### Problem 2
##### Modeling cancer cell growth

In [1]:
import numpy as np
p = np.array([[9/10,1/10,0],[0,7/8,1/8],[2/5,0,3/5]])
p50 = np.linalg.matrix_power(p,50)
print(p50)

[[0.48780487 0.3902439  0.12195122]
 [0.4878049  0.3902439  0.12195121]
 [0.48780484 0.39024392 0.12195124]]


#### Simulating 10,000 hours

0.35179


In [27]:
import numpy as np
import random
    
# X = State: 0: Growing, 1: Sequencing, 2: Dividing
X = [0]
N = 10000

def bernoulli_rv(p):
    """  
    Do a Bernoulli trial with rate of success of p (0,1)
    """
    u = random.uniform(0,1)
    if u<p:
        return 1
    else:
        return 0


for i in range(N):
    if X[-1] == 0:
        change_to_S = bernoulli_rv(1/10)
        if change_to_S:
            X.append(1)
        else:
            X.append(0)
    elif X[-1] == 1:
        change_to_D = bernoulli_rv(1/8)
        if change_to_D:
            X.append(2)
        else:
            X.append(1)
    else:
        change_to_G = bernoulli_rv(2/5)
        if change_to_G:
            X.append(0)
        else:
            X.append(2)

print(f'Time in G = {X.count(0)}')

Time in G = 4856
